[Variables]
; Please put your location code of OpenWeatherMap below, e.g: London, GB is 2643743.
; You can check it on OpenWeatherMap.com. Search for your city and the id will be in the url 
; e.x. https://openweathermap.org/city/2643743

; Borrowed code from the Persona 5 Calendar Rainmeter Skin.
; https://github.com/Mive82/Persona-5-Calendar

LocationCode=Paste Here!

; You also have to get a free API key by registering
ApiKey=Paste Here!

TimeFormat1224=12

Units=metric
