[Variables]
; Please put your location code of OpenWeatherMap below, e.g: London, GB is 2643743.
; You can check it on OpenWeatherMap.com. Search for your city and the id will be in the url 
; e.x. https://openweathermap.org/city/2643743

; Borrowed code from the Persona 5 Calendar Rainmeter Skin.
; https://github.com/Mive82/Persona-5-Calendar

LocationCode=2013348

; You also have to get a free API key by registering
ApiKey=c1e4f61c8cb75c05096ec8c69493f2a8

TimeFormat1224=12

Units=metric
