[Variables]
; Please put your location code of OpenWeatherMap below, e.g: London, GB is 2643743.
; You can check it on OpenWeatherMap.com. Search for your city and the id will be in the url 
; e.x. https://openweathermap.org/city/2643743

; Borrowed code from the Persona 5 Calendar Rainmeter Skin.
; https://github.com/Mive82/Persona-5-Calendar

LocationCode=2643743

; You also have to get a free API key by registering
ApiKey=6309c0d21bcd4babf2ee5cdefc38dc49
