function Initialize()
    -- add a new ame JINE chat here.
    a = {}
    a[1] = "i just woke up but I already wanna go back to bed let me die pls ww"
    a[2] = "i cbf streaming today but if i dont im gonna get overtaken by the other streamers... help me p-chan"
    a[3] = "i cant think of any interesting ideas for future streams! what should i do..."
    a[4] = "fuck everything lets just watch some anime!!!!!!!!!! i love anime!!!!!!!!!!!!!!!!!!!!!"
    a[5] = "ive been trying really hard, dont you think? ive already done enough right?? pien~"
    a[6] = "lets have ramen tonight... im gonna get the worlds biggest fucking bowl of ramen"
    a[7] = "dreamt that this bear suddenly attacked me and when i killed it and ripped it open you were inside covered in blood and i was like oh fuck i need to hold a funeral and when i went online to ask people how to do a funeral they all started bashing me wtf"
    a[8] = "i want to do what i love most for the rest of my life... lying around and doing nothing and sleeping"
    a[9] = "i want yooou (i want yooou) i need yoouu (i need yooouu) i love yooouuu (i love yooouu) atamaaa nooo naaakaaa"
    a[10] = "why are adults always so annoying!!! we'll never grow up to be like them right p-chan?"
    a[11] = "its not like i hate people asking me to collab with them or anything but i always forget to reply to their messages and then they get really mad at me... why is life so hard"
    a[12] = "im really horny today!!! lets fuck!!!!!"
    a[13] = "my stash is running out help"
    a[14] = "i always act like i dont care about getting a lot of likes or followers but tbh i do. like a lot."
    a[15] = "found a thread about me but im too scared to read it ;-; pls look for me"
    a[16] = "i blocked all the haters but im scared theyll somehow get back at me for it... i even had a dream about them......"
    a[17] = "i think i messed up your mediflicks recommendations coz i was using your account to watch stuff im sorry (pien~)"
    a[18] = "i took some sneak shots of you when you were asleep and nearly uploaded them to kangels account oops"
    a[19] = "if i were a fighting game character id be a zoner that people love to use to poke at their opponents from afar but the moment they have to play against me theyd throw a fit hahaha"
    a[20] = "heres your pachinko allowance sweetie♪ (money money)"
    a[21] = "maybe i should open my next stream by screaming I WANNA DIE!!!!!"
    a[22] = "what if i used my super chat money to buy a vibrator"
    a[23] = "i was thinking maybe i should learn how to play mahjong so i can stream it but i can already imagine all the backseat gamers in the chat :( teach me how to play sometime?"
    a[24] = "the construction is SO ANNOYING!!! i s2g im suing the ministry of transport if someone uses the noise to dox us"
    a[25] = "feel like akibas more of tourist trap now than the anime wonderland it used to be... so sad ):"
    a[26] = "i wanna get hiiiiiigggghhhh"
    a[27] = "u up?"
    a[28] = "put topkek on my wishlist as a joke and someone actually got some for me? lets eat it for dessert tonight"
    a[29] = "kimi to natsu no owari blagh (dies)"
    a[30] = "forgot that i was supposed to go see my shrink today oops"
    a[31] = "woke up to someone who used to be a big fan of mine bashing me to hell and back? what did i do... actually nvm ive stirred a lot of shit lmao..."
    a[32] = "they say that money cant buy happiness but its not like happiness is the only thing you need to get in life"
    a[33] = "i want an aquarium can we get an aquarium?? though i guess we dont really have the time or know how to start one... but can we have sushi five... no wait four times a week? please?"
    a[34] = "maybe i should stick to taking cough medicine only when i actually have a cough"
    a[35] = "you know, p-chan, ive always really- *clank clank clank clank* (sound of a train rushing past)"
    a[36] = "im gonna hit whoever says that hate is part of the fame are you stupid??? why dont you go tell off the haters instead???? every hater should be legally obligated to give me one billion yen"
    a[37] = "Today, I saw the ocean. I'm not afraid anymore."
    a[38] = "got a bunch of letters in the mail that say something about taxes? and the national pension? is this one of those things that i have to pay?"
    a[39] = "did you mute my notifs? i just sent you a message but your phone didnt go off? explain????"
    a[40] = "woke up and saw that i had crushed my alarm clock under my knee... how did that even happen"
    a[41] = "maybe i should get into a little voice acting to make my streams more interesting? but im already spreading my brain cells thin for love and work~ so busy~"
    a[42] = "can we not stream today??? day off! day off! day off! i need to blow off some steam!"
    a[43] = "someone thought i was in high school yesterday lol"
    a[44] = "feel like i need at least 18 hours of sleep every day"
    a[45] = "im out of depaz :( cant... move..."
    a[46] = "when you think about it, ordering super spicy ramen even when you know that itll burn off your tongue before you can finish it is kinda like a form of self harm"
    a[47] = "the parts of my room that dont show up on camera are getting so messy... but making everyone think you have a neat room is an art in and of itself"
    a[48] = "can you buy me some eel? i worked really hard on streaming today!! go to the supermarket and get me the biggest one they have!!!"
    a[49] = "oh no im a cat now i cant do anything meow meow"
    a[50] = "i woke up on record time this morning! praise me pls"
    a[51] = "all these people from the underground idol scene keep dming me!!! maybe i should write -no fuckboys- in my bio"
    a[52] = "abracadabra my room is now 166sqm (i wish)"
    a[53] = "i swear i dont mean to always push the laundry onto you;; i do want to do it sometimes please dont hate me;;; dont block me;;;;;"
    a[54] = "youre not looking at my dms as quickly as you used to dont you care about your adorable girlfriend anymore"
    a[55] = "can you pick up some eggs today theyre on sale pls and thank u!!"
    a[56] = "i really want a cat but i know ill just end up making you take care of it all the time so nvm"
    a[57] = "maybe i should be like -i want a million yen!!!!- in all of my streams it couldnt hurt to try right"
    a[58] = "my room is so messyyyy i want a roomba but i dont think it could get over the mess..."
    a[59] = "maybe i should just drop everything and go frolick in a grassy plain somewhere for the rest of my life"
    a[60] = "ive been trying to perfect making that -shoop- sound tweeter makes when you refresh it"
    a[61] = "ame-chan seems tired... you should let her take a break :<"
    a[62] = "maybe i should start pandering to the delinquent demographic or something instead of the gamer nerds"
    a[63] = "bitches be like looking for cafes with nice interiors just to take selfies in im bitches"
    a[64] = "bitches be like having 174539 side tweeters im bitches"
    a[65] = "bitches be like following every single account their SO follows im bitches"
    a[66] = "bitches camera rolls be only filled with gacha game screenshots im bitches"
    a[67] = "youre not looking at my dms as quickly as you used to dont you care about your adorable girlfriend anymore"
    a[68] = "im gonna lobotomize everyone and make it so that the only streamer they can enjoy is kangel"
    a[69] = "some fuckboy streamer just dmed me asking if i would go to a concert with him"
    a[70] = "if he gives me a million yen i might consider it"
    a[71] = "im so tired of being a streamer im gonna become a cosplayer instead :<"
    a[72] = "did you know that if you ask for decaf they give you coffee thats been decaffeinated? huge if true"
    a[73] = "maybe i should get into train photography instead"
    a[74] = "apparently the selfie apps the super popular cosplayers use are all free?? thought it would be p2w... i would p2w..."
    a[75] = "i need to pee can you go pee for me instead wwwww"
    a[76] = "bucket list: have a girls night out at a love hotel"
    a[77] = "saw a couple going to therapy at the clinic the other day!!!"
    a[78] = "couldnt sleep so i tried to think of stuff that is more valuable than money. my conclusion? nothing."
    a[79] = "said i dropped out of preschool as a joke on stream and the haters actually thought i was being serious LMAO"
    a[80] = "the weather today is so nice for going out but... the internet... it calls to me..."
    a[81] = "maybe i should call kangels haters demons haha get it"
    a[82] = "someone i know spends 200,000 yen on underground male idols every month but theyve only ever given kangel 100 yen in the super chat... i see how it is..."
    a[83] = "LIFE stands for Losing Initiative Fuck Everything"
    a[84] = "ill do my best watching tv so do your best cleaning the bath p-chan!! you can do it!!"
    a[85] = "thought that reading the poetry i wrote in middle school would make for a fun stream but when i went to look them over i cringed so hard i nearly died so nvm"
    a[86] = "ive been falling asleep with my eyes open so if you see me doing that pls close my eyes for me thank u mwah"
    a[87] = "i think its good that you arent handing out days off like candy...that being said, can i please have the day off today :<<<<"
    a[88] = "apparently with this -credit card- thing we can buy anything we want? lets give it a spin!"
    a[89] = "some guy in america messaged me on dinder... are they actually going to fly to japan? if they do i think they deserve a meetup based on that alone"
    a[90] = "im just a fat little caterpillar"
    a[91] = "my special talent: knowing the difference between dopamine, endorphins, and serotonin"
    a[92] = "i cant believe youre still with me... is it because im just that cute? :<"
    a[93] = "alcohol is worse than drugs imo"
    a[94] = "i forgot to pay the water bill so now we have no running water!!! hahaha i fucked up..."
    a[95] = "one day we'll be one of those couples that can afford to call a taxi to go wherever we want..."
    a[96] = "curry for dinner tonight! and tomorrow! and the day after!"
    a[97] = "NOT CLICKBAIT lying down is super comfy and now i cant get up?! come help me up pls :(("
    a[98] = "the tax payment notice went from being yellow to red?! should i be worried???"
    a[99] = "please tell me that this is real and im not just some girl in an asylum pretending to be a streamer called kangel please tell me youre real"
    a[100] = "maybe i should just spam the #depressionpals hashtag"
    a[101] = "whenever i see someone posting hate about me and i find out that theyre over 30 i actually start feeling really bad for them"
    a[102] = "people who bash fast food and cheap restaurants just want to pretend theyre rich lol"
    a[103] = "you can only succeed online if you can use every situation to your advantage, no matter how bad it is"
    a[104] = "any time someone tells me -thats YOUR opinion- ill just reply with -yep and im right!-"
    a[105] = "sometimes ill have this moment of self-awareness and realize that all ive got going for me is my face and then i get really depressed"
    a[106] = "if you want to win at life you gotta take direct action."
    a[107] = "im gonna FISH around for something interesting on the net"
    a[108] = "LETS GO TO SPACE WHEN WE GET RICH!!! and them im gonna ask the aliens to please destroy earth"
    a[109] = "being a streamer is so good bc you can deduct anything you want!!! not sure what for, but ill take it!"
    a[110] = "adults piss me off so bad UGH theyre all disgusting scum and yet they still want to act like theyre hot shit"
    a[111] = "people who rt my posts but dont like are practically asking to be mauled"
    a[112] = "i heard that next year theyre gonna start putting men who dm other girls behind their gfs backs on death row"
    a[113] = "my social security is 666"
    a[114] = "girls who are like -omg i just dont get fat i guess- ok... show us the back of your hand then."
    a[115] = "if you died then i think i would just lose it so ive decided that no matter what i will die before you do."
    a[116] = "i love seeing female voice actors making posts that stir nerds up lmfao"
    a[117] = "its time for dinneeerrr im serving up salad fingers ;) with a rusty spoon :D"
    a[118] = "bitches be posting emo song lyrics after a breakup id probably be bitches"
    a[119] = "what if i started a stream off by by screaming THIS AINT A FUCKIN ZOO!!!!"
    end
function Update()
    math.randomseed(os.time())
    math.random(); math.random(); math.random()

-- Randomizes from the JINE chats.
    return a[math.random(1,#a)]
    end

    -- a[7] currently has the longest string.
    -- a[27] currently has the shortest string.